[package]
name = "retroval"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
csv = "1.3.1"
plotters = "0.3.7"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.138"
